version: '3.3'
services:
  web:
      image: positive/otus-nginx:php
      ports:
          - "80:80"
      networks:
          - front
      volumes:
        - ./code:/code
  
  php:
      image: php:7-fpm
      networks:
          - front
      volumes:
        - ./code:/code

networks:
  front:
