---
# tasks file for rsyslog-server

- name: Install rsyslog package
  yum:
    name: rsyslog

- name: Make sure rsyslog is enabled
  systemd:
    enabled: true
    name: rsyslog

- name: Install rsyslog server config
  copy: src=rsyslog_server.conf dest=/etc/rsyslog.conf
  when: inventory_hostname == "log"
  notify:
    - restart rsyslog

- name: Install rsyslog client config
  copy: src=crit.conf dest=/etc/rsyslog.d/crit.conf
  when: inventory_hostname == "web"
  notify:
    - restart rsyslog
