# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinux => {
    :box_name => "centos/7",
    :ip_addr => '192.168.11.101',
  },
}

Vagrant.configure("2") do |config|
  #config.vm.synced_folder '.', '/vagrant', disabled: true

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s

      box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
          yum install -y vim epel-release
          cd /vagrant
          cp monitor /etc/sysconfig/
          cp monitor.service /etc/systemd/system/
          cp monitor.sh /usr/local/bin/
          cp monitor.timer /etc/systemd/system/
          systemctl enable monitor && systemctl start monitor
          systemctl enable monitor.timer && systemctl start monitor.timer
      SHELL

    end
  end
end

