version: '3.3'
services:
  web:
      image: positive/otus-nginx:php
      ports:
          - "80:80"
      networks:
          - front
      volumes:
        - ./php:/code

  phpserver:
      image: php:7-fpm
      networks:
          - front
      volumes:
        - ./php:/code

  goserver:
      image: positive/otus-go
      ports:
          - "9001:9001"
      networks:
          - front

  rubyserver:
      image: positive/otus-ruby
      ports:
          - "9002:9002"
      networks:
          - front

networks:
  front:
