---

- name: NGINX | Install and configure NGINX
  hosts: web
  become: true
  roles:
    - auditd
    - nginx

- name: Rsyslog | Install and configure Rsyslog Server
  hosts: log
  become: true
  roles:
    - rsyslog-server
