---

- name: NGINX | Install and configure NGINX
  hosts: web
  become: true
  roles:
    - auditd
    - nginx

- name: Rsyslog | Install and configure Rsyslog
  hosts: all
  become: true
  roles:
    - rsyslog

- name: ELK | Install and configure ELK stack
  hosts: all
  become: true
  roles:
    - elk
