---
# tasks file for nginx

- name: Install EPEL Repo package from standard repo
  yum:
    name: epel-release
    state: present

- name: Install nginx package from epel repo
  yum:
    name: nginx-1.12.2
    state: installed
  tags:
    - nginx-package
    - packages
  notify:
    - restart nginx

- name: NGINX | Create NGINX config file from template
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  tags:
    - nginx-configuration
  notify:
    - reload nginx
