# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :master => {
    :box_name => "centos/7",
    :ip_addr => '192.168.11.150'
  },
  :slave => {
    :box_name => "centos/7",
    :ip_addr => '192.168.11.151'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s

      #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

      box.vm.network "private_network", ip: boxconfig[:ip_addr]

      box.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        # Подключаем дополнительные диски
        #vb.customize ['createhd', '--filename', second_disk, '--format', 'VDI', '--size', 5 * 1024]
        #vb.customize ['storageattach', :id, '--storagectl', 'IDE', '--port', 0, '--device', 1, '--type', 'hdd', '--medium', second_disk]
      end

      box.vm.provision "shell", run: "always", inline: <<-SHELL
        mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
        cp /vagrant/vagrant_rsa /root/.ssh/id_rsa
        cat /vagrant/vagrant_rsa.pub >> /root/.ssh/authorized_keys
        chmod 600 /root/.ssh/id_rsa*
        yum install https://repo.percona.com/yum/percona-release-latest.noarch.rpm -y
        yum install Percona-Server-server-57 Percona-Server-selinux-56 vim -y
        cp /vagrant/conf/conf.d/* /etc/my.cnf.d/
        if [ ${HOSTNAME} == 'slave' ]; then
          sed -i 's/server-id = 1/server-id = 2/g' /etc/my.cnf.d/01-base.cnf
          echo "replicate-ignore-table=bet.events_on_demand\nreplicate-ignore-table=bet.v_same_event" >> /etc/my.cnf.d/05-binlog.cnf
        fi
        systemctl start mysql
        oldpassword=$(cat /var/log/mysqld.log | grep 'root@localhost:' | awk '{print $11}')
        newpassword="Otus123%^"
        mysqladmin password "${newpassword}" -p${oldpassword}
        mysqladmin -p${newpassword} flush-privileges
        if [ ${HOSTNAME} == 'master' ]; then
          mysql -p${newpassword} -e "CREATE DATABASE bet"
          mysql -p${newpassword} -D bet < /vagrant/bet.dmp
          mysql -p${newpassword} -e "CREATE USER 'repl'@'%' IDENTIFIED BY '${newpassword}'"
          mysql -p${newpassword} -e "GRANT REPLICATION SLAVE ON *.* TO 'repl'@'%' IDENTIFIED BY '${newpassword}'"
          mysqldump -p${newpassword} --all-databases --triggers --routines --master-data --ignore-table=bet.events_on_demand --ignore-table=bet.v_same_event > /vagrant/master.sql
        fi
        if [ ${HOSTNAME} == 'slave' ]; then
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null 192.168.11.150:/vagrant/master.sql /vagrant/master.sql
          mysql -p${newpassword} < /vagrant/master.sql
          mysql -p${newpassword} -e "CHANGE MASTER TO MASTER_HOST = '192.168.11.150', MASTER_PORT = 3306, MASTER_USER = 'repl', MASTER_PASSWORD = '${newpassword}', MASTER_AUTO_POSITION = 1"
          mysql -p${newpassword} -e "START SLAVE"
        fi
      SHELL
    end
  end
end
